apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proksi.fullname" . }}
  labels:
    {{- include "proksi.labels" . | nindent 4 }}
data:
  config.yaml: |
    # HTTP server bind address to serve Proksi
    bind: ":{{ .Values.service.containerPort }}"

    # Log level for application logging
    # Options: debug, info, warn, error, fatal
    log_level: {{ .Values.logLevel | quote }}

    # Config of exposing Prometheus metrics
    metrics:
      enabled: {{ .Values.metrics.enabled }}
      bind: "0.0.0.0:{{ .Values.metrics.containerPort }}"

    # Storage backend type: "elasticsearch" or "stdout"
    # Use "stdout" to output JSON logs directly to stdout instead of Elasticsearch
    storage_type: {{ .Values.storageType | quote }}

    # List of upstreams to proxy the request to them
    upstreams:
      # main is the upstream that we are sure about its behavior and its response will be the criterion. The response of the
      # request will be the main upstream response
      main:
        address: {{ .Values.upstreams.main.url | quote }}
      # test is the upstream that we want to test its behavior. Its response will be compared to the main upstream response
      test:
        address: {{ .Values.upstreams.test.url | quote }}

    # Worker pool configurations
    worker:
      count: {{ .Values.worker.count }}                  # Number of go-routines of the pool
      queue_size: {{ .Values.worker.queueSize }}         # Size of the queue (buffered channel size)

    # Elasticsearch storage config params
    elasticsearch:
      addresses: {{- range.Values.elasticsearch.addresses }}
        - {{.}}{{- end }}
      username: {{ .Values.elasticsearch.username | quote }}
      password: {{ .Values.elasticsearch.password | quote }}

    # List of JSON paths that we don't want to compare
    skip_json_paths:
      {{- range .Values.skipJsonPaths }}
      - {{ . }}
      {{- end }}
    
    # Percentage of the requests that will be sent to the test upstream
    test_probability: {{ .Values.testProbability }}

    # Indicates whether to log response body of main and test upstreams or not.
    log_response_payload: {{ .Values.logResponsePayload }}

    # Indicates whether to compare response headers between main and test upstreams or not.
    compare_headers: {{ .Values.compareHeaders }}

    # Global configuration for all routes
    global_config:
      compare_headers: {{ .Values.globalConfig.compareHeaders }}
      skip_headers:
        {{- range .Values.globalConfig.skipHeaders }}
        - {{ . }}
        {{- end }}
      store_req_body: {{ .Values.globalConfig.storeReqBody }}
      store_resp_bodies: {{ .Values.globalConfig.storeRespBodies }}
      skip_json_paths:
        {{- range .Values.globalConfig.skipJsonPaths }}
        - {{ . }}
        {{- end }}
      test_probability: {{ .Values.globalConfig.testProbability }}

    # Routes to skip entirely (no test upstream call)
    skip_routes:
      {{- range .Values.skipRoutes }}
      - {{ . }}
      {{- end }}

    # Per-route configuration overrides
    route_configs:
      {{- range $route, $config := .Values.routeConfigs }}
      "{{ $route }}":
        {{- if $config.compareHeaders }}
        compare_headers: {{ $config.compareHeaders }}
        {{- end }}
        {{- if $config.skipHeaders }}
        skip_headers:
          {{- range $config.skipHeaders }}
          - {{ . }}
          {{- end }}
        {{- end }}
        {{- if $config.storeReqBody }}
        store_req_body: {{ $config.storeReqBody }}
        {{- end }}
        {{- if $config.storeRespBodies }}
        store_resp_bodies: {{ $config.storeRespBodies }}
        {{- end }}
        {{- if $config.skipJsonPaths }}
        skip_json_paths:
          {{- range $config.skipJsonPaths }}
          - {{ . }}
          {{- end }}
        {{- end }}
        {{- if $config.testProbability }}
        test_probability: {{ $config.testProbability }}
        {{- end }}
      {{- end }}
